name: Playwright test
on:
  push:
    branches:
    - master
    - Teddy_playwright_testing

jobs:
  e2e-tests:
    runs-on: macos-latest # or ubuntu-latest, windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node 16.x # Specifies node versions
        uses: actions/setup-node@v3

      - uses: microsoft/playwright-github-action@v1  # uses 

      - name: Install package
        run: yarn add -D @playwright/test # Installs playwright tests

      - name: Download browsers
        run: npx playwright install # Downloads browsers
        
      - name: Install dependencies and run tests
        run: npx playwright test tests # Run tests
